import cv2
img = cv2.imread("sun.jpg")
startRow = int(177*.15)
startCol = int(284*.15)
endRow = int(177*.85)
endCol = int(284*.85)
croppedImage=img[startRow:endRow,startCol:endCol]
rotationMatrix=cv2.getRotationMatrix2D((284/2,177/2),60,0.5)
rotatedImage=cv2.warpAffine(img,rotationMatrix,(284,177))
edge_img = cv2.Canny(img,100,200)
cv2.imshow('Original Image', img)
cv2.imshow('Cropped Image', croppedImage)
cv2.imshow('Rotated Image', rotatedImage)
cv2.imshow("Detected Edges", edge_img)
rotationMatrix2=cv2.getRotationMatrix2D(((endCol-startCol)/2,(endRow-startRow)/2),60,0.5)
rotatedImage2 = cv2.warpAffine(croppedImage,rotationMatrix2,((endCol-startCol),(endRow-startRow)))
edge_img2 = cv2.Canny(rotatedImage2,100,200)
cv2.imshow("Full Combo", edge_img2)
cv2.waitKey(0)
